spring.application.name=actualizarBases

spring.datasource.url=jdbc:mariadb://localhost:3306/matriz_cd
#spring.datasource.url=jdbc:mariadb://localhost:3306/batch
spring.datasource.username=root
spring.datasource.password=Truper*2025
##########spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#     Truper12345
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080
